import = ["/home/plarpoon/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 150
lines = 30
