#. "$HOME/.cargo/env"
export PATH="$HOME/.npm-global/bin:$PATH"
export JAVA_HOME="/usr/lib/jvm/java-21-openjdk-21.0.3.0.9-1.fc40.x86_64/"
#export PATH="$PATH:~/Git/quickemu/quickget"
#export PATH="$PATH:~/LunarG/x86_64/bin/"
